version: '1.0.{build}'

image: Visual Studio 2017

init:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

platform:
  - x64

configuration:
  - Debug
  - Release

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user
  - conan remote add systelab-bintray https://api.bintray.com/conan/systelab/conan
  - conan --version

build_script:
  - ps: conan export-pkg conanfile.py TestUtilitiesInterface/$env:appveyor_build_version@systelab/stable -s build_type=$env:configuration

deploy_script:
  - ps: >- 
      if($env:appveyor_repo_tag -eq 'True') {
        conan upload TestUtilitiesInterface/%APPVEYOR_BUILD_VERSION%@systelab/stable --all -r systelab-bintray
      } else {
        echo "Not uploading because this is not a tag build"
      }
