language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    language: python
    compiler: gcc
    python: "3.7"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - COMPILER_NAME=gcc-7
      - BUILD_TYPE=Release
      - CONAN_BUILD_TYPE=Release
      - COMPILER_LIBCXX=libstdc++11

install: 
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - pip install conan
  - conan user
  - conan remote add systelab-public https://csw.jfrog.io/artifactory/api/conan/cpp-conan-production-local --insert 0
  - conan --version

script:
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      conan export-pkg conanfile.py "TestUtilitiesInterface/${TRAVIS_TAG:1}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX};
    else
      conan export-pkg conanfile.py "TestUtilitiesInterface/0.0.${TRAVIS_BUILD_NUMBER}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX};
    fi

deploy:
  - provider: script
    script: conan upload "TestUtilitiesInterface/${TRAVIS_TAG:1}@systelab/stable" --all -r systelab-public --force
    on:
      tags: true
  - provider: script
    script: bash ./ci/build_docs.sh -o "systelab" -s "cpp-test-utilities" -t "${TRAVIS_TAG}" -c "Travis" -n "${COMPILER_NAME} ${BUILD_TYPE}" -j "${TRAVIS_JOB_ID}"
    skip_cleanup: true
    on:
      tags: true
