language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - CONAN_BUILD_TYPE=Release
      - COMPILER_LIBCXX=libstdc++11

  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - CONAN_BUILD_TYPE=Debug
      - COMPILER_LIBCXX=libstdc++11

  - os: osx
    osx_image: xcode10.1
    compiler: clang   
    env:
      - CONAN_BUILD_TYPE=Release
      - COMPILER_LIBCXX=libc++

install:
  - pip install conan --user
  - conan user
  - conan remote add systelab-bintray https://api.bintray.com/conan/systelab/conan
  - conan --version

script:
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      conan export-pkg conanfile.py "TestUtilitiesInterface/${TRAVIS_TAG:1}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX};
    else
      conan export-pkg conanfile.py "TestUtilitiesInterface/0.0.${TRAVIS_BUILD_NUMBER}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX};
    fi

deploy:
  provider: script
  script: conan upload "TestUtilitiesInterface/${TRAVIS_TAG:1}@systelab/stable" --all -r systelab-bintray --force
  on:
    tags: true